version: '3.8'

services:
  base-executor:
    build:
      context: ./executors
      dockerfile: Dockerfile
    image: base

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    environment:
      - MAX_WORKERS=4

  python-executor:
    build:
      context: ./executors/python
      dockerfile: Dockerfile
    image: code-executor-python
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined