services:
  runnerbase:
    build:
      context: ./runners
      dockerfile: Dockerfile
    image: baserunner

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    environment:
      - MAX_WORKERS=4

  python:
    build:
      context: ./runners/python
      dockerfile: Dockerfile
    image: pythonrunner
